# Generated by Django 6.0.3 on 2026-03-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('temprature', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('temprature', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('temprature', models.FloatField(null=True)),
            ],
        ),
    ]
