# Generated by Django 6.0.4 on 2026-04-13 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualdata",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="monthlydata",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="seasonaldata",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ]
            ),
        ),
    ]
