# Generated by Django 6.0.4 on 2026-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('Tmax', 'Tmax'), ('Tmin', 'Tmin'), ('Tmean', 'Tmean'), ('Rainfall', 'Rainfall'), ('Sunshine', 'Sunshine'), ('Raindays1mm', 'Raindays1mm'), ('AirFrost', 'AirFrost')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('°C', '°C'), ('mm', 'mm'), ('hours', 'hours'), ('days', 'days')], max_length=20, unique=True),
        ),
    ]
